//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exercise_app.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("exercise_app.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainings App.
        /// </summary>
        internal static string app_title {
            get {
                return ResourceManager.GetString("app_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        internal static string button_back {
            get {
                return ResourceManager.GetString("button_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        internal static string button_save {
            get {
                return ResourceManager.GetString("button_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diastolisch.
        /// </summary>
        internal static string diastolic {
            get {
                return ResourceManager.GetString("diastolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainigsdauer.
        /// </summary>
        internal static string duration {
            get {
                return ResourceManager.GetString("duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivitäten.
        /// </summary>
        internal static string exercises {
            get {
                return ResourceManager.GetString("exercises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sportart.
        /// </summary>
        internal static string exerciseType {
            get {
                return ResourceManager.GetString("exerciseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herzfrequenz.
        /// </summary>
        internal static string heartrate {
            get {
                return ResourceManager.GetString("heartrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notizen.
        /// </summary>
        internal static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systolisch.
        /// </summary>
        internal static string systolic {
            get {
                return ResourceManager.GetString("systolic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uhrzeit.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainings Details.
        /// </summary>
        internal static string view_detail_title {
            get {
                return ResourceManager.GetString("view_detail_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Hinzufügen.
        /// </summary>
        internal static string view_exercise_input_title {
            get {
                return ResourceManager.GetString("view_exercise_input_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        internal static string view_list_add_button {
            get {
                return ResourceManager.GetString("view_list_add_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainings Übersicht.
        /// </summary>
        internal static string view_list_title {
            get {
                return ResourceManager.GetString("view_list_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitalwerte hinzufügen.
        /// </summary>
        internal static string view_vitals_input_title {
            get {
                return ResourceManager.GetString("view_vitals_input_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vital Werte.
        /// </summary>
        internal static string vitals {
            get {
                return ResourceManager.GetString("vitals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewicht.
        /// </summary>
        internal static string weight {
            get {
                return ResourceManager.GetString("weight", resourceCulture);
            }
        }
    }
}
